AWSTemplateFormatVersion: "2010-09-09"
Description: "S3 and DynamoDB Backend for Terraform State"

Resources:
  TerraformStateBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "tf-labs-state-juan"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    DeletionPolicy: Retain

Outputs:
  TerraformStateBucketName:
    Description: Name of the S3 bucket for Terraform state
    Value: !Ref TerraformStateBucket
