name: Deploy Bastion Host
on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Greeting
        run: echo "Hello, World!"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::760508986718:role/gh-actions-role
          role-session-name: GitHubActions_tf_labs
          aws-region: ${{ env.AWS_REGION }}

      - name: STS GetCallerIdentity
        run: aws sts get-caller-identity
