name: Deploy Bastion Host
on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  WORKSPACE: ./bastion_host

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::760508986718:role/gh-actions-role
          role-session-name: GitHubActions_tf_labs
          aws-region: ${{ env.AWS_REGION }}

      - name: STS GetCallerIdentity
        run: aws sts get-caller-identity

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.WORKSPACE }}
